<a href="https://colab.research.google.com/github/siddhidamkondwar/Statistics-/blob/main/stact_lec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name = 'ERPData')

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
x1 = df.MaterialID

NameError: name 'df' is not defined

In [ ]:
np.unique(x1)    #Q.How many unique material ids are there

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
len(np.unique(x1))   #lenght of unique material id

6

In [ ]:
np.unique(x1, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [ ]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

In [ ]:
df1 = x1.value_counts().reset_index()

In [ ]:
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

Proportional

In [ ]:
df1['prop'] = df1['count']/sum(df1['count'])

In [ ]:
df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    GCVB-79      5  0.10
5    LXCV-21      5  0.10

In [ ]:
df1['pct'] = df1['prop']*100

In [ ]:
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [ ]:
x2 = np.array([4,7,5,2,3,8])

In [ ]:
np.cumsum(x2)      #cumilative sum

array([ 4, 11, 16, 18, 21, 29])

In [ ]:
df1['CumPct'] = np.cumsum(df1['pct'])

In [ ]:
df1

  MaterialID  count  prop   pct  CumPct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

In [ ]:
df2 = df1.sort_values('pct',ascending=False).head(3)

In [ ]:
df1.iloc[1]

MaterialID    AXCP-78
count              11
prop             0.22
pct              22.0
CumPct           52.0
Name: 1, dtype: object

In [ ]:
# CENTRAL TENDANCY - MEAN ,MEDIAN , MODE
#dispersion or variation or spread -  range , inter quartile range , variance and std variance
# shaape - skewness and kurtosis

In [ ]:
x =np.array([3,4,5,6])
f=np.array([20,18,9,12])

In [ ]:
mean = sum(x*f)/sum(f)

In [ ]:
mean

np.float64(4.220338983050848)

In [ ]:
import copy #shallow copy

In [ ]:
a=[1,2,3]

In [ ]:
b=a.copy()

In [ ]:
b

[1, 2, 3]

In [ ]:
b.append(4)

In [ ]:
a

[1, 2, 3]

In [ ]:
b

[1, 2, 3, 4]