<a href="https://colab.research.google.com/github/siddhidamkondwar/Statistics-/blob/main/Stat_30_5_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
from numpy import random
from collections import Counter
from numpy.linalg import inv
from numpy.linalg import eig
import matplotlib
from matplotlib import pyplot as plt
import seaborn as sns
import pylab
from pylab import legend
from pylab import plot, show, title, xlabel, ylabel
import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t,expon,f
from sklearn.model_selection import train_test_split
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

# PAIRED T TEST

In [ ]:
before = np.array([12,14,10,9,8,13])

In [ ]:
after = np.array([11.8,9.7,11.3,8.2,7.2,12.3])

In [ ]:
#Ha avg (before - after ) >= 2
# Ha avg (agter - before ) < 2 ============>left tail test

In [ ]:
d = (before - after)
d

array([ 0.2,  4.3, -1.3,  0.8,  0.8,  0.7])

In [ ]:
np.mean(d)

np.float64(0.9166666666666665)

In [ ]:
ssw.ttost_paired(before,after,low=2,upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [ ]:
(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),        #---------->p value for right tail test
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),           #test statistics
  np.float64(0.10453031697930062),        #-----------------> p value for left tail test
  np.float64(5.0)))                            #Degrees of freedom

In [ ]:
scipy.stats.ttest_1samp(before - after ,popmean=2,alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

In [ ]:
(np.mean(d)-2)/((np.std(d,ddof=1))/6**0.5)

np.float64(-1.4413160909218492)

In [ ]:
t.cdf(-1.4413160909218492,5)

np.float64(0.10453031697930062)

# One way ANOVA (ANalysis Of VAraince)

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

In [ ]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])

In [ ]:
df

  Col1  Col2
0    A    22
1    A    29
2    A    10
3    A    28
4    A    11
5    A    17
6    A    18
0    B    34
1    B    20
2    B    33
3    B    28
4    B    37
5    B    20
6    B    27
7    B    36
8    B    25
0    C    24
1    C    28
2    C    21
3    C    16
4    C    28
5    C    17
6    C    23
7    C    18

In [ ]:
mod1 = ols('Col2 ~ Col1',df).fit()

In [ ]:
tbl = sm.stats.anova_lm(mod1)

In [ ]:
print(tbl)

            df     sum_sq     mean_sq         F    PR(>F)
Col1       2.0  405.30754  202.653770  5.120029  0.015446
Residual  21.0  831.19246   39.580593       NaN       NaN

In [ ]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [ ]:
print(pairwise_tukeyhsd(df.Col2, df.Col1))

 Multiple Comparison of Means - Tukey HSD, FWER=0.05
=====================================================
group1 group2 meandiff p-adj   lower    upper  reject
-----------------------------------------------------
     A      B   9.6032 0.0168   1.6116 17.5947   True
     A      C   2.5893   0.71  -5.6178 10.7964  False
     B      C  -7.0139 0.0787 -14.7193  0.6916  False
-----------------------------------------------------

In [ ]:
df = pd.read_excel("/content/data_anova .xlsx")

In [ ]:
df.head()

  Col1  Col2
0    A    10
1    A    23
2    A    14
3    A    25
4    A    22

In [ ]:
df = pd.read_excel("/content/data_anova .xlsx")

In [ ]:
df

   Col1  Col2
0     A    10
1     A    23
2     A    14
3     A    25
4     A    22
5     A    11
6     A    12
7     B    26
8     B    39
9     B    29
10    B    39
11    B    31
12    B    32
13    B    38
14    B    22
15    B    25
16    C    21
17    C    23
18    C    26
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [ ]:
grp1 = df.groupby('Col1')

In [ ]:
grp1.agg('mean')

           Col2
Col1
A     16.714286
B     31.222222
C     23.250000

In [ ]:
gm = np.mean(df.Col2)           #grand mean

In [ ]:
sm = grp1.agg('mean')            #sample mean

In [ ]:
sm.loc['A']

Col2    16.714286
Name: A, dtype: float64

In [ ]:
7*(sm.loc['A']-gm)**2 +9*(sm.loc['B']-gm)**2 +8*(sm.loc['C']-gm)**2

Col2    842.849206
dtype: float64

In [ ]:
df = pd.read_excel('data_anova .xlsx')

In [ ]:
df.index = np.arange(df.shape[0])

In [ ]:
grp1 = df.groupby('Col1')
samp_mean = grp1.agg('mean')

In [ ]:
grand_mean = np.mean(df.Col2)

In [ ]:
7*(samp_mean.loc['A']-grand_mean)**2 +9*(samp_mean.loc['B']-grand_mean)**2 +8*(samp_mean.loc['C']-grand_mean)**2

Col2    842.849206
dtype: float64

In [ ]:
sampA = df.Col2[np.where(df.Col1=='A')[0]]

In [ ]:
sampB = df.Col2[np.where(df.Col1=='B')[0]]

In [ ]:
sampC = df.Col2[np.where(df.Col1=='C')[0]]

In [ ]:
sum((np.array(sampA) - np.array(samp_mean.loc['A']))**2) + sum((np.array(sampB) - np.array(samp_mean.loc['B']))**2) + sum((np.array(sampC) - np.array(samp_mean.loc['C']))**2)

np.float64(684.484126984127)

In [ ]:
842.849 + 684.484

1527.333

In [ ]:
sum((np.array(df.Col2) - np.array(grand_mean))**2)

np.float64(1527.3333333333333)

In [ ]:
mod1 = ols('Col2 ~ Col1',df).fit()

In [ ]:
tbl = samp_mean.stats.anova_lm(mod1)

AttributeError: 'DataFrame' object has no attribute 'stats'

In [ ]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})

In [ ]:
df = pd.DataFrame({'Resp': zoo, "Factor1" : supp, "Factor2" : lake})

In [ ]:
model = ols('Resp~Factor1+Factor2',df).fit()

In [ ]:
res = sm.stats.anova_lm(model)

In [ ]:
print(res)

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN

In [ ]:
 n